-d C:\Users\Md. Jannatul Nayem\Downloads\picorv32-infer_sram\picorv32-infer_sram\impl\gwsynthesis\picorv32.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Md. Jannatul Nayem\Downloads\picorv32-infer_sram\picorv32-infer_sram\src\picorv32.cst
-cfg C:\Users\Md. Jannatul Nayem\Downloads\picorv32-infer_sram\picorv32-infer_sram\impl\pnr\device.cfg
-sdc C:\Users\Md. Jannatul Nayem\Downloads\picorv32-infer_sram\picorv32-infer_sram\src\picorv32.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
